excluded:
  - Pods
  - Client/Pods
  - Server/Pods
  - Specs
  - Client/Teztez/Resources/Generated
  - Templates
  - Tests
included: 
  - Client/Teztez
  - Server
whitelist_rules:
  - closure_spacing
  - closure_parameter_position
  - cyclomatic_complexity
  - colon
  - empty_enum_arguments
  - empty_parentheses_with_trailing_closure
  - fatal_error_message
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - file_length
  - identifier_name
  - implicit_getter
  - implicitly_unwrapped_optional
  - large_tuple
  - legacy_constant
  - legacy_constructor
  - line_length
  - operator_usage_whitespace
  - redundant_string_enum_value
  - redundant_void_return
  - redundant_type_annotation
  - return_arrow_whitespace
  - trailing_newline
  - syntactic_sugar
  - trailing_closure
  - type_contents_order
  - type_name
  - type_body_length
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - unused_closure_parameter
  - unused_import
  - unused_optional_binding
  - void_return
  - yoda_condition

warning_threshold: 20
file_length:
  warning: 250
  error: 250
function_body_length:
  warning: 25
  error: 25
identifier_name:
  excluded:
    - id
    - ru
    - vc
line_length:
  warning: 150
  error: 150
type_body_length:
  warning: 250
  error: 250
type_name:
  excluded:
    - T
large_tuple:
  warning: 3
  error: 3
